spring:
  application:
    name: ecosystem-service
      datasource:    driver-class-name: org.h2.Driver    url: jdbc:h2:mem:testdb
    username: sa
    password:    
    
      jpa:    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:      ddl-auto: update
    generate-ddl: true
    show-sql: true
    
jwt:  
  secret: kakaopay
  validHour: 3